version: '3.8'

services:
  training:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./configs:/app/configs
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python train.py --model_name resnet50 --num_classes 2 --batch_size 32 --learning_rate 0.001 --epochs 100 --data_dir data --output_dir checkpoints 